# Homebrew formula for Mollow (CLI).
# Publish this file in: github.com/ingeniousfrog/homebrew-tap/Formula/mollow.rb
# Regenerated by packaging/render-homebrew-formula.sh (see docs/homebrew.md).

class Mollow < Formula
  desc "Cross-platform machine inspection and performance-baseline CLI"
  homepage "https://github.com/ingeniousfrog/Mollow"
  license "Apache-2.0"
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/ingeniousfrog/Mollow/releases/download/v0.1.4/mollow-aarch64-apple-darwin.tar.gz"
      sha256 "8147762bb1efc91b5f106d2ac5d39acfcc963e2e2646b2e5329d24626c6f5a22"
    end
    on_intel do
      url "https://github.com/ingeniousfrog/Mollow/releases/download/v0.1.4/mollow-x86_64-apple-darwin.tar.gz"
      sha256 "e691286a1062bb0059ad0fe6af944b9f88b11969863edf47da0099759054da28"
    end
  end

  on_linux do
    url "https://github.com/ingeniousfrog/Mollow/releases/download/v0.1.4/mollow-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "dfe8f2d2860567ddef86f80b9c71406cf0aa3d32c52bd85b028faf16f6e5e130"
  end

  def install
    bin.install "mollow"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mollow --version")
    assert_match "inspect", shell_output("#{bin}/mollow --help")
  end
end
